# Disabling Autocorrect in Zsh
unsetopt correct_all

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Alias command of start VSCode.
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}

# about openssl
export CFLAGS="-I$(brew --prefix openssl)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix openssl)/lib $LDFLAGS"

# golang
export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"

# python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# pyenv-virtualenv init
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# rbenv init
eval "$(rbenv init -)"
alias rbenv_install="RUBY_CONFIGURE_OPTS=\"--with-openssl-dir=`brew --prefix openssl` --with-readline-dir=`brew --prefix readline`\" rbenv install -f"
